### ISSUE TITLE
Code style discussion

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#100]
I generally try to avoid discussions about code style, I think that the default Resharper settings are almost always the way to go.

But, being a Go developer also, I have started to like forced braces on conditionals.
e.g. 

```csharp
if (x) 
{
     Foo();
}

//vs

if (x)
   Foo();
```

My personal opinion is that it adds a nice symmetri to the code.

Another thing I personally like to see, is to use C# 7 features when possible.
e.g. "throws expressions" for null validation. named tuples etc.

Thoughts?
Is this something we can do or am I too damaged by Go? :)

**Comment by adamhathcock** [comment]
I always say conditionals should be forced.  Code merge situations can easily change if statements without braces.  The braces usually make code not compile on mismerges.

C# 7 features are too good not to use.

**Comment by adamhathcock** [comment]
I mean "force braces on any nested structure" including loops, etc.

**Comment by rogeralsing** [comment]
What about API surface.

Return arrays or `IReadonlyList<T>` ?

e.g.
```csharp
public string[] GetNodes()
//vs..
public IReadonlyList<string> GetNodes()
```

And how far should we push it on in params?
Allow `IEnumerable<T>` on args of more than one elements rather than arrays?

Internally, we could know that we only use arrays and avoid allocations in favor for a more restricted API.
On the other hand, having a generalized codebase could be nice in the long run.

Thoughts?

**Comment by adamhathcock** [comment]
To be really "correct" I guess readonly lists but i hate coding with them.  If people modify the array then they're really killing themselves.  How much rope do we give people to hang themselves?

I prefer enumerables as parameters.  Let the receiver rebuffer the data if they have to.  The receiver should be doing that anyway to guarantee their own copy. 

Of course that is subject to perf.

It almost feels like there is a low level and high level set of APIs.  Like what is there is low level with arrays.  What I'm attempting with DI and a MediatR approach is high level.  Maybe think of the API and guidance in that way?

**Comment by cpx86** [comment]
I agree about the style preferences above :)

Regarding collection types, we should actually avoid arrays because creating them is more expensive than lists. Internally I don't see any problem with having Lists as return types, although for public members we should probably strive for IReadOnlyCollection.

**Comment by cpx86** [comment]
A correction: populating arrays is more expensive than lists (because of bounds-checking).  OTOH, a List will have a few more allocations. So I guess we'd need to profile it to see which is more important.

Yes the user shouldn't be given mutable collections, but that can be solved by only having the readonly interfaces on public signatures.
