### ISSUE TITLE
Identity Lookup strategies

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#1250]
Some thoughts on alternative identity lookup strategies:

* Gossip-based identity lookup. All locations are gossipped across all nodes, how do we deal with activation control?

* Partition Identity lookup, as is, but how to deal with large workloads? paginated handovers?

* Partition Identity without the indirection. Owning the ID means owning the actor itself.

**Comment by mhelleborg** [comment]
I think the third alternative is very interesting. With our consistent hashing we will actually not reposition any actors if a node is removed. Identity rebalance can also happen completely locally, and the node itself can just remove any misplaced actors. 

It is not a strategy which will work for every use case, and does not support local affinity etc, but for a certain set of applications this is a very good alternative. Perhaps it will trigger us to rethink some of our interfaces, since the `Cluster.GetAsync` way of doing it would trigger two round trips to the owning member..

**Comment by mhelleborg** [comment]
Paginated handovers btw: https://github.com/asynkron/protoactor-dotnet/pull/1254

**Comment by rogeralsing** [comment]
Done
