### ISSUE TITLE
No way currently to clear blocked list

### ISSUE THREAD

**Issue by chaseaucoin** [AsynkronIT/protoactor-dotnet#1398]
## Expected Behavior
If a node has recovered or is addressable it should be able to be removed from the blocked list. 

## Actual Behavior
When using a stateful service in Kubernetes and proto actor if I scale the system to 0 then add any arbitrary set of nodes it operates fine, but if a node is moved or if the service is updated during the period of the node becoming healthy the gossip channel will mark the node in the blocked list on all other nodes and then it can never recover. Having programmatic access to clean the block list would be nice. 

## Specifications

  - Version: 0.26.0
  - Platform: Ubuntu 20.04 Container on EKS  -

**Comment by rogeralsing** [comment]
Blocking is on a member ID level, the idea is that if a member for some reason leaves the cluster, this _specific_ member instance may not re-join.
This is much due to how virtual actors work. if some actors existed on this node before, and now exists elsewhere in the cluster as this member left. if it were to be allowed to rejoin, there would have to be coordination on which instance of this actor is the correct one.

Instead, we opted for the simpler approach, once a member leaves, it may never rejoin, and should be downed.

A new node may very well rejoin again on the same host and port, but this member will have a different member id as this is a new instance (ID is an autogenerated GUID, so this part is handled automatically)
This applies to rolling upgrades of pods also.

Are you seeing any case where a newly started pod may not join the cluster?

**Comment by chaseaucoin** [comment]
Yes. When the existing pod is restarted the new instance with a new ID is not reaching gossip consensus and then gets banned. But if I scale to 0 and then up to any arbitrary amount (I have tested 1,2,5, and 10 nodes) then joining of new nodes works fine.

**Comment by chaseaucoin** [comment]
I'm doing some testing with a fairly pessimistic readiness probe to see how that alters the behavior.

**Comment by chaseaucoin** [comment]
So I was able to resolve why the gossip was happening out of band. I think that since the containers I'm using have 1 core the cluster task was blocking starting the web server so I moved the start logic to a hosted service which resolved this like so. I still wonder in practice though how should I receive a signal and restart nodes that have failed gossip so that I don't get a split brained cluster?

`
public class HostedCluster : IHostedService
    {
        private ActorSystem _actorSystem;
        Task _startTask;

        public HostedCluster(ActorSystem actorSystem)
        {
            _actorSystem = actorSystem;
        }

        public async Task StartAsync(CancellationToken cancellationToken)
        {
            _startTask = _actorSystem.Cluster().StartMemberAsync();
        }

        public Task StopAsync(CancellationToken cancellationToken)
        {
            return Task.CompletedTask;
        }
    }
`
