### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by rfrerebe-stx** [AsynkronIT/protoactor-dotnet#1562]
Hello,

I see that we can use [Router for IActor](https://github.com/asynkron/protoactor-dotnet/blob/dev/examples/Router/Program.cs) , but is it possible to use Router for Grain ?

**Comment by rogeralsing** [comment]
Hi @rfrerebe-stx , no, there is no way to use a router for Virtual Actors / Grains.
You could however create an actor that behaves like a router, which routes messages to a list of grain identities.
e.g. that is what we are doing in the Cluster PubSub feature.

There is no fundamental reason why Routers cannot do this. we could theoretically have Group routers that accepts ClusterIdentities instead of just PIDs.

**Comment by rfrerebe-stx** [comment]
Thanks 👍
