### ISSUE TITLE
Request order guarantee?

### ISSUE THREAD

**Issue by AqlaSolutions** [AsynkronIT/protoactor-dotnet#1978]
Is there a guarantee that sequentially invoking grain methods without awaiting their result will cause them to be processed in the same order by the grain instance? I see there is an await for PID in the `RequestAsync` which can cause misordering in this case but it happens only when `PidCache` doesn't have the pid. In which scenarios pid may be lost from the `PidCache`? What can I do to ensure this ordering without awaiting for each request result?

```
var someGrain = _cluster.GetSomeGrain("A");
var task1 = someGrain.Method(1);
var task2 = someGrain.Method(2);
var task3 = someGrain.Method(3);
await Task.WhenAll(task1, task2, task3);
```

```
public async Task<ResponseMessage> Method(int value)
{
   Console.WriteLine(value); // this should print 1, 2, 3
   return new ResponseMessage { Value = value * value };
}
```

In my opinion, method calls should be queued somewhere before doing anything asynchronous in the `RequestAsync`. Actors concept is all about queues (mailboxes) on the receiver side but it's broken if at the sender side you can't "enqueue" multiple requests in a correct order.

It looks like sending itself should either be synchronous with returning a task only for response waiting or there should be two separate tasks returned - one for sending and one for awaiting the response. Or the approach with "outgoing mailbox" can be used (queuing requests before trying to send them).

![image](https://user-images.githubusercontent.com/3465565/235111413-615e83e8-781c-43a7-b995-1db3b488a1ec.png)

**Comment by rogeralsing** [comment]
If you have a PID to the target actor, the order is guaranteed.

However, when using virtual actors with non-awaited RequestAsync for the following reason, it will not be guaranteed

Let's say the actor PID is present in the PidCache,
1. Call1 sends a request to the actor. this request is now on the remote writer queue for the target node.
2. The remote node where the actor should be, leaves the cluster (for whatever reason, redeploy, crash, etc).
3. the calling member detects this, clears the pid cache
4. Call2 sends a request to the actor. the cache is now empty, the PID is resolved again, now to a new location
5. Call2 completes as it has contact with the new location of the actor
6. Call1 will fail to be delivered, deadletter, and the RequestAsync will retry, now to the new PID
7. Call1 will retry, and complete for the new PID. but will be completed _after_ Call2, since you did not await the tasks


That being said, it will _mostly_ be in order, assuming the system is stable.

But there is no way for us to efficiently handle these edge-cases

**Comment by AqlaSolutions** [comment]
If we decide not to use Proto.Remote, will the PID lookup be always completed synchronously or can it still cause misordering?

**Comment by rogeralsing** [comment]
I'm confused about what features you are using, we are now talking about in-process, remote, and cluster.

in-process and remote, do have ordering guarantees.
cluster with awaited ReuqestAsync has order guarantees.

cluster with non-awaited ReuqestAsync does not.

**Comment by AqlaSolutions** [comment]
Sorry, I mean that your example

> The remote node where the actor should be, leaves the cluster (for whatever reason, redeploy, crash, etc).

will not be possible because there is only a single local node. In this case is it safe to assume ordering when not awaiting grain methods?

**Comment by rogeralsing** [comment]
>In this case is it safe to assume ordering when not awaiting grain methods?

yes, but why would you be using cluster for a single node? that completely defies the purpose of it.

**Comment by AqlaSolutions** [comment]
Because grains are more friendly to use and you can't have them without a cluster. E.g. you don't have to spawn them manually and they have generated RPC methods.
