### ISSUE TITLE
Sending message to "type of actor" instead to specific actor?

### ISSUE THREAD

**Issue by wind-rider** [AsynkronIT/protoactor-dotnet#266]
Probably I'm confused between the concepts of actors and cluster grains (I'm new to these concepts), but I'm wondering why it is needed to manually spawn actors and to call Tell on those specific instances.

I thought that the goal was to process a certain message / workload (independent of who does it) instead of controlling everything manually?

I'm looking for a framework to set up a kind of "message processing pipeline" where actors (not sure if I'm using the right term) pick up a message from a queue (proto.actor mailbox?), process it, and pass it on without knowing what actor instance will process it.

**Comment by rogeralsing** [comment]
That is exactly what the cluster does. 
You call `Cluster.Get("name","type name")` which gives you a PID to a named actor of the specified type "somewhere" in the cluster.

**Comment by wind-rider** [comment]
ok, that is clear. Could you refer me to some explanation about what specific actor instances are used for then?

What makes them different from creating an object from another class that has an async method called `Tell` with a certain message parameter that can perform some work?

Also - could you explain the difference between the ClusterGrainHelloWorld and ClusterHelloWorld examples? There is not much documentation and I find it difficult to understand why the differences in approach between these examples are used.

**Comment by rogeralsing** [comment]
ClusterHelloWorld just use the cluster semantics to resolve a normal actor somewhere in the cluster.
you get a PID which you can interact with.
Sending a message to this PID may or may not work as the actor could die or the node could crash from the time you get the PID.

In ClusterGrainHelloWorld, there is a Typed grain which you interact with through a typed client.
This interaction is RPC based, a request and a response is given.
This allows grains to retry or make sure the request was handled.
In the Go API, the grain client will allow you to retry x times before giving up and raising an error.

This will be possible in the C# API too, we need to extend the grain generator to support this.

But that is the main difference.

* Untyped, fire and forget messaging
vs
* Typed, request response with retries

In both cases the actors/grains are bound to the actor concurrency model, one message/request at a time per instance.
Each instance is identified by a unique name.
You can have multiple actors/grains of the same type but with unique names in order to process data in parallell.

**Comment by wind-rider** [comment]
Ok, that helps :)

Two more questions
- is there a form of "cluster management" (spinning up a new node when it is requested or when another node of the same type dies)
- why is it needed to name nodes when requesting them with `Cluster.Get[Async]("name","type name")`? Or isn't that needed when using `GetRandomActivatorAsync`?

**Comment by rogeralsing** [comment]
The name is not the name of the node, it is the name of a unique actor/grain.

The cluster consists of multiple nodes (machines) and on those machines there are multiple grains/actors.
The grains/actors can be of different types.

If you request a grain/actor which have not been requested before (a new name that is) it will be created for you.

Adding / removing actual machines to the cluster is an operational thing.
As long as the code running on those machines can join the cluster, that should be fine

**Comment by rogeralsing** [comment]
See #325
