### ISSUE TITLE
Restarting as a SystemMessage

### ISSUE THREAD

**Issue by fthoms** [AsynkronIT/protoactor-dotnet#273]
I think it would be an idea to have all system messages inherit from SystemMessage. This makes it easier to filter out, but more importantly it will make the semantics of a system message more explicit. The reason for this post is that Restarting does not inherit from SystemMessage.

**Comment by rogeralsing** [comment]
We will look into this.
In Go, the Restarting message implements AutoReceiveMessage, in .NET it does not.
There is also a no clear definition when something should be a SystemMessage or an AutoReceiveMessage right now. this needs to be more clearly defined.

cc @AsynkronIT/developers

**Comment by fthoms** [comment]
I can take a look at it, and perhaps submit a pull request if I find a possible solution that fits with AutoReceiveMessage and SystemMessage. I guess the .net and go versions should be as alike as possible, so I will keep that in mind.

**Comment by cpx86** [comment]
One thing I've been thinking about is: what is the need to differentiate between system/user messages on a type level? To me it seems that the two main reasons for having two types of messages is 1) system messages take priority over user messages, and 2) system messages are processed only by the context, whereas user messages are always forwarded to the actor instance.

Another thing that bugs me is that system messages currently only make sense when you're dealing with actors (and even then it's more of an internal implementation detail, since you shouldn't send them directly), whereas e.g. a non-actor process might not care about them, or a non-default mailbox might not respect the priority. It feels like a pretty big leaky abstraction to me.

**Comment by fthoms** [comment]
I believe there is a good reason for differentiate between system messages and user messages, namely that the client should be able to filter out system messages and just handle the user messages. But assigning priorities to messages depending on their origin is not a good idea, since the premise of an actor is to handle messages in a strict sequential manner. I can't see any scenario where one type of message needs to take precedence over another, except in the client code.

I get the idea of having the context handle system messages. However, there are a number of scenarios where the actor needs to know if it is stopping, of if it has been restarted. The beauty of the choice to hand any message to the client code is that it is simple; There is only one way to deal with messages, and that's it. One of the things that bugs me a bit with akka is that we have to deal with these system events (restart, pre-handle-message etc) in a totally other way than just handling messages. While this is not a problem as such, it adds unnecessary complexity. Keep it simple, seems to be the mantra of proto.actor, and I love it.

Well, this is just my take on it. I don't know if this is the reasoning when designing proto.actor, but it would be if I was designing it.

**Comment by tomliversidge** [comment]
> the client should be able to filter out system messages and just handle the user messages.

Well this is achieved by just not handling the system messages right? Or have i missed something?

Rather than filtering out, I'd ask almost the opposite - are there scenarios when an actor would want to do something for _all_ messages of a given type (i.e. System or User)? I think @cpx86 was asking whether we need to separate this at a type level. i.e. if we're handing them down for the actors themselves, do we _need_ type differentiation? An actor can handle a Started message regardless of whether it inherits from a base type of SystemMessage or not.

**Comment by fthoms** [comment]
@tomliversidge The problem here is that not all system messages inherit from SystemMessage, so filtering them out is a problem. I would like to do the following in my actors:

```
if(message is SystemMessage) return Task.CompletedTask;
<handle user message normally>
...
```
but that is, currently, not possible.

However, I *would* like to actually get the system messages so that my actor can be notified when for example the actor is about to stop, and handle any clean up accordingly. If this is not done via a SystemMessage that is also handed to the client code in the actor, then I would need to do it fx. via a middleware component. While this is all well, it is another way of handling what is basically a message.

I get the idea of not differentiating on the type, but then my if-/switch statement would have to explicitly filter out all system messages, i.e. Started, Stopping, Stopped, Restarted etc. An besides, using the type system like this tells client code developers that this is a special message that most probably have already been handled by the framework, but you are given it anyway to do stuff as an afterthought.

**Comment by tomliversidge** [comment]
I don't understand why you need to explicitly filter out the messages. Can you just not handle them? Or do you have some code that runs for all user message types?

**Comment by rogeralsing** [comment]
In either way, we should create a more clear definition of the base messages.

e.g. should lifecycle events like starting, stopped, restarting have some special base/interface?

**Comment by cpx86** [comment]
It would be nice to separate the system commands from the lifecycle events yeah.

**Comment by rogeralsing** [comment]
We have `Terminated` which is a SystemMessage, but is also exposed to the user code. which is a bit weird.
A lot of heritage from Akka on this stuff

**Comment by tomliversidge** [comment]
> should lifecycle events like starting, stopped, restarting have some special base/interface?

marker interface would work? this would give actors the opportunity to filter on them (i'm presuming c#7 pattern matching allows this) and remain flexible

**Comment by tomliversidge** [comment]
And for the record, these are the current system messages?

- Started
- Stop
- Terminated
- Watch
- Unwatch
- Failure
- Restart
- SuspendMailbox 
- ResumeMailbox
- Continuation 

Some of which are passed to the user message handling process, but not all.

**Comment by cpx86** [comment]
From what I can gather there are three types of messages:
1) user messages, which are sent to the actor
2) system messages, which are prioritized over user messages and are never sent to the actor.
3) lifecycle events, which are sort of a sub-type of system messages in that they are prioritized over user messages (via the system mailbox queue), but they are also sent to the actor.

Does the above sound correct to you guys?

**Comment by fthoms** [comment]
@cpx86 Could you please elaborate on why system messages should have priority over user messages? IMHO they are just messages, and should be processed in sequence, regardless of origin. But I might miss some crucial detail here.

@tomliversidge Looks about right :-)

**Comment by cpx86** [comment]
@fthoms The reason is for controlling the actor lifecycle. E.g. when stopping an actor it should shut down without continuing to process any user messages still in the mailbox. So the `Stop` message needs to take priority over any pending user messages. Another example is supervision, e.g. if an actor is failing then the mailbox must stop processing all messages until the supervisor has decided how to handle the failure.

**Comment by fthoms** [comment]
@cpx86 I don't agree with you there: if you spawn an actor, send it 10 messages to process, and immediately after that you `Stop` it, the messages you previously sent it are discarded since `Stop` has higher priority. This directly contradicts how an actor system should work, and that is also not how akka works, or Erlang/OTP for that matter.
It would be more clean to just have the actor process these messages in sequence.

**Comment by tomliversidge** [comment]
It's how Akka.net works? http://getakka.net/docs/working-with-actors/stopping-actors

**Comment by adamhathcock** [comment]
@fthoms Stopping by the system has to be higher priority than normal messages.  If the queue is maxed out to something like ONE MILLION messages then you have to wait to process those (which may never happen which is why the actor is getting stopped) which is wrong.

As @tomliversidge points out, there is a PoisonPill mechanism that behaves as you wish.  

Akka.NET and Akka behave this way: http://doc.akka.io/docs/akka/current/java/actors.html#stopping-actors

**Comment by fthoms** [comment]
@tomliversidge & @adamhathcock  Yeah, there seems to be some confusion here. We are talking about stopping in a normal flow, for example when sending a Stop message to an actor, which is the same as a PoisonPill in akka.net. THIS is what I meant, and what we are discussing.

The other situation, where you have to kill/terminate an actor prematurely is another flow entirely, and should be handled by the system behind the scenes without involving client (actor) code.

What ever things are called, we do agree :-)

**Comment by alexeyzimarev** [comment]
Maybe it is time to fix it? We got some issues today. Also, I believe that the PoisonPill should be a system message too.

**Comment by rogeralsing** [comment]
>I believe that the PoisonPill should be a system message too.

The reason why PoisonPill is not a system message is to allow consumption of all user messages before the pill.
To get a system message level stop, then there is the `Stop` system message.
