### ISSUE TITLE
Example of DependencyInjection can not run correctly

### ISSUE THREAD

**Issue by blueskoo** [AsynkronIT/protoactor-dotnet#323]
The ctor of EventStream is interal result in this issue.

![eventstream](https://user-images.githubusercontent.com/2750239/30896896-e4533332-a385-11e7-983b-0cf39fa094ce.JPG)

**Comment by rogeralsing** [comment]
cc @adamhathcock

**Comment by adamhathcock** [comment]
@rogeralsing this is because the public constructor of EventStream<> was changed to internal.  I guess the intent is to have a static `Instance` but I wanted to have it in the DI container.  However, I can't register an open generic with a factory to have the proper type to make `EventStream<>` closed.

I guess I can just change EventStream to not be in the DI container but I'd rather use IoC.

I guess the decision is to keep the constructor hidden or just can't use EventStream<> in the generic MS.Extensions.DependencyInjection registration.

**Comment by spbsmile** [comment]
any update ? example still contains an error

**Comment by masteryee** [comment]
PR open: #387

**Comment by rogeralsing** [comment]
Merged and fixed
