### ISSUE TITLE
Multi cluster support

### ISSUE THREAD

**Issue by jinhong-** [AsynkronIT/protoactor-dotnet#366]
Hi, interesting project you got there. Are you guys planning for multi cluster support? I noticed you guys are using singletons for clusters. This makes it hard to do dependency injections as well

**Comment by rogeralsing** [comment]
Please elaborate, what is the usecase and what do you want to accomplish

Some context that might be worth knowing:
There are some deliberate design decisions at play when it comes to singletons in Proto.Actor.
One of the main painpoints when we developed Akka.NET was that in order to have ActorSystems and related primitives, the serialization layer must be able to re-attach deserialized ActorRefs (PID's in our case).

In essence this means that if there is an ActorRef/PID somewhere inside a message with a deep object structure, any such instance must be found and re-attached to the actorsystem.

This can be done, but requires custom serializers and quite a bit of black magic.

Early on in the design phase of the project, we decided to not go down that route, instead keeping

**Comment by jinhong-** [comment]
One possibility is the idea of "microservices", where each service has it's own clusters. But I guess this is solved by the cluster name if i am not wrong. While working with this though i noticed another major issue with using static classes. I can't seem to be able to mock Cluster nor PID. I suppose i can wrap another layer above this but is there any "TestKit"?

**Comment by Skareeg** [comment]
Multiple clusters could potentially be used so that a single application can act as a control point between a cluster of GPU enabled devices (that will have some form of specialized processing) and a cluster of standard non-GPU computers (for general processing). The singleton clusters do help with ease of use, but do not allow for separation of hardware. If there is a better way for me to go about this, please let me know. Otherwise, this framework is excellent.

**Comment by cpx86** [comment]
This discussion has been dead for a while and it's not clear what is being proposed. From my POV the purpose of Proto.Cluster is to enable a set of processes to act as a single unit scaled across multiple identical hosts (VMs, pods, containers) where all processes are identical and replaceable. Compare it e.g. to how distributed systems like Kafka, RabbitMQ, Consul, etc consider clusters. Hope this clarifies something.

Closing. Please re-open the discussion if you disagree.

**Comment by alexeyzimarev** [comment]
I think that Cluster should be scoped inside the `ActorSystem` and by doing so we'll resolve this issue.

**Comment by cpx86** [comment]
@alexeyzimarev That could probably be done - although I do find the idea of running multiple clusters across a single process as well as running a single cluster across multiple processes... strange :)

**Comment by alexeyzimarev** [comment]
I agree that it's a bit weird conceptually, although should be perfectly doable technically :)

**Comment by Damian-P** [comment]
Running multiple remotes and cluster instances on a single process is possible with the code in #498.
Actually in a project I changed the remote unit tests to run multiple remotes from the same process.
It can be easily done for the cluster too.

**Comment by rogeralsing** [comment]
I didn't even think of this, being able to run multiple nodes in the same process would make life so much easier for cluster and remote test and debugging.
