### ISSUE TITLE
Remote.SpawnNamedAsync fail after 10 ProcessNameAlreadyExist

### ISSUE THREAD

**Issue by jrouaix** [AsynkronIT/protoactor-dotnet#369]
I have something really weird here :
![devenv_2017-12-27_15-27-27](https://user-images.githubusercontent.com/2705498/34384664-d9e8a992-eb1d-11e7-9e04-8f272745cfd5.png)

**Comment by jrouaix** [comment]
After 10 Remote.SpawnNamedAsync() with the same name, all next calls will timeout.

**Comment by PotterDai** [comment]
I think this is because Activator actor is using default supervisor strategy, which will kill itself after 10 failures. This can be fixed by using a custom strategy. I will try make a PR for this issue when I got some time. = )

**Comment by PotterDai** [comment]
@rogeralsing Hey Roger, so this problem is a bit tricky. Default supervisor strategy has a failure cap of 10, if we want to prevent Activator from stop, I only came up 2 ways:
1 - Change default supervisor strategy (Easiest way to implement)
2 - Create a supervisor for Activator. (Ideally this supervisor should supervise all system actors, but will require a bit amount of code changes and increase complexity)
What do you think?

**Comment by rogeralsing** [comment]
I've been thinking about the root actor supervision for a long time.
The idea of a parent supervising the children comes from Akka, in Erlang this is not an explicit case.
Erlang allows any actor to supervise another actor (afaik, not a big Erlang user)
In ProtoActor supervision has been somewhat extracted, we have an interface for it.

Maybe the right solution is to be able to pass such supervision instance to the actor to be created.

props.withSelfSupervisior(...)

or..

props.withParent(parentPid)

The latter set the actors parent to the passed pid, this way, we could have a system supervisor actor that act as some form of foster parent to actors created with the above approach.

Thoughts?

**Comment by jrouaix** [comment]
Ho, I didn't see the ProcessNameExistException was rethrown !

I'd be glad to inject any kind of supervision implementation but for this remote activation problem, could the activator just send the response and swallow ProcessNameExistException ?

It seems to me it a normal thing to have multiple call for the same actor name (let's say I have 12 distinct client instances on this one ?). Perhaps also it's a questionable design to throw an exception on an expected situation ?

**Comment by rogeralsing** [comment]
>activator just send the response and swallow ProcessNameExistException ?

It should, for clustering we even have semantics for that so you get status codes back.
This should be the behavior of the remote activator too.
https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/src/Proto.Cluster/Cluster.cs#L72

can we push that behavior down into the activator or into some activator API?
cc @PotterDai

**Comment by PotterDai** [comment]
@jrouaix @rogeralsing  Just made a quick PR to fix the NameExist error handling.
We should still keep this issue open since 10 error cap problem still exists, and Activator will still suffer problem when there are 10 failures (which is very possible)

@rogeralsing How can this be implemented in a clean way? Currently only spawning actor within parent actor (using context.Spawn) can result in parent/child relationship, shall we create a new way to allow child be instantiated using Actor.Spawn?

**Comment by rogeralsing** [comment]
@PotterDai not sure yet. but I do think it would be enough if the parent pid is passed to the spawned actor. 
the parent itself does not need to keep track of the child in this case.
(Havent really thought this through, but technically that should work)

**Comment by PotterDai** [comment]
@rogeralsing However this will lead to some other problems.
For example user kill the parent actor, and since that parent does not keep track of its children, its children will not be killed.

**Comment by rogeralsing** [comment]
True, but it could also be a private system actor function for our internal use.
or, we could make sure that "guardians" cannot be killed

just brainstorming :)

**Comment by PotterDai** [comment]
@rogeralsing That's interesting! = ) So we can create a custom actor type like Future called Guardian, and make it not killable, and each one have a specific SupervisorStrategy.

**Comment by rogeralsing** [comment]
exactly

**Comment by PotterDai** [comment]
@rogeralsing 
Hey Roger, I think this pr(https://github.com/AsynkronIT/protoactor-go/pull/211) should be good to go and this issue can be closed = )

**Comment by jrouaix** [comment]
Thank you guys.
