### ISSUE TITLE
Dynamically add/remove kind from cluster

### ISSUE THREAD

**Issue by potterdai** [AsynkronIT/protoactor-dotnet#388]
Hey @rogeralsing, @BorisTasevski in Gitter brings up this topic about add/remove kind during runtime, the use case is
1. dynamically load/unload dlls.
2. a root actor that can change the behaviour of the node. In Behaviour A, node can spawn kind (A1, A2, A3), in Behaviour B, node can spawn kind (B1, B2, B3).
3. etc....

For Case1: since majority of protoactor's codes are in static, which means that will be pretty difficult to unload a dll in a clean way,  shall we promote this behaviour?

For both cases: It requires cluster to treat kinds not like a constant, will this lead to any consistency issue?

**Comment by rogeralsing** [comment]
Hmmm. what would be the main use case here?
.NET does not upport unloading assemblies, unless you run in a separate appdomain.
appdomains are afaik, only part of .NET old, things might have changed since I looked at that though.

**Comment by potterdai** [comment]
Quoted from @BorisTasevski in Gitter
>Well, i've had some look at the underlying code. By the look of things, making some parts of static class Partition public could possibly make it happen. But, i haven't had the time for a thorough look... Also, i don't think that dlls are to be blamed, or questioned... I've just made that kind of implementation. You could write all of actors, but what if i don't want the cluster members to know about some of them at all for a long time? Or to know about them at a particular time? For example making some actions only possible in some particular state of the state machine... I know, passing the messages to actors, and then they not responding... But what if the actors are completely unaware of the state of the system(which they should, after all, be, if i am not mistaken), and they receive message at a wrong time? The questions pop into my head, i am not even quite sure that those are the right questions :grinning: Anyways, adding and removing particular actors to cluster, after it has been started, that is basically the only question :grinning: Should that behavior be allowed, or not. That is all. Sorry for longer post.

**Comment by rogeralsing** [comment]
Ok so more in terms of having a cluster wide state machine rather than having unloadable assemblies then.

I still think we should try to come up with a real world use case and work from there.

In the same way that the actors are unaware of state on the outside, we could argue that the remote activator in ProtoActor is also an actor (conceptually) and is equally unaware of outside state.
So where and when would the state change and decide what props are visible?

cc @BorisTasevski

**Comment by potterdai** [comment]
@rogeralsing  The main feature-request is that user can add/remove kinds in a node from cluster during runtime.

Load/unload dlls is one use case, another is that there is a root actor that can change the behaviour of the node. In Behaviour A, node can spawn kind (A1, A2, A3), in Behaviour B, node can spawn kind (B1, B2, B3).

However in current Protoactor's cluster, kinds are treated like a constant, once started, can never be changed.

**Comment by BorisTasevski** [comment]
@rogeralsing Hello, it's probably better to continue here, rather than to overload the project chat. Even the state machine here is not of any real importance. 

I want to expand the functionality of the system in run-time. I have 100 actions encapsulated with actors. I want to make 5 new ones and add them to Cluster without the need to restart the cluster. That is the clear downtime of the system. Not to mention the messages that are already in the mailboxes of the actors, that are going to be lost, or the wait until the restart of the system until all of the messages are responded to. Like I've said, my current solution is to add one "Parent" Actor, responsible for all other actors, to Cluster, and at starting of the system add all of the existing actors as children to the parent. At runtime, i just add all of the new ones as children, as well. When members of the cluster request for one of the actions, they contact the Parent Actor, and the parent responds with the PID of the requested actor. From there on, the communication goes from cluster member to child actor directly. The problem i see here is the bottleneck, which is Parent Actor. All of the requests must go through it. 

I hope i made it a bit clearer :)

@PotterDai You've summarized it much better than I did :)

**Comment by potterdai** [comment]
@BorisTasevski   cc @rogeralsing 

I did a quick implementation for this feature. And hereby is several discovers:
Overall **ClusterAddKind** flow looks like this:
```
1. Call ClusterAddKind()
2. Register kind props in Remote
3. Spawn Partition Actor in Cluster
4. Update Membership in Consul
5. Members(Nodes) receive Membership Update event
6. Partitions transfer local PIDs to new remote Partition depends on its location
```
Overall **ClusterRemoveKind** flow looks like this:
```
1. Call ClusterRemoveKind()
2. Remove Membership in Consul
3. Members(Nodes) receive Membership Update event
4. Partitions either transfer local PIDs to new remote Partition or stop it, 
   depends on its location
5. Stop Partition Actor from Cluster
6. Deregister kind props from Remote
```
The main concern here is around **ClusterAddKind's step 6** and **ClusterRemoveKind's step 4**. During this step, all nodes holds that kind will need to be re-balanced, a lot of grains will need to be stopped. I think this is better be handled at application level, like you restart that node container/pod/app.
By introducing it as a method, it will simply encourage user to over-use it, which will greatly increase the chance of problems like duplicate grains, inconsistency, etc, and also very hard to predict exactly when this removing process will be finished, so that we can move-on to step 5 and step 6.

-------------
So regarding what you want to do, a workaround is that there is a [MemberStrategyBuilder](https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/src/Proto.Cluster/ClusterConfig.cs#L23), which allows you to customize MemberStrategy for each kind. So what you can do is let your member(node) periodically check from a central key-value store(ex. Consul) if a kind is available in each member(node), and adjust where to spawn your new grain accordingly.

The drawback is that you cannot stop the already created grains through this method. So you have to implement your own local grain management class/actor, like a root actor, to cache/stop them. = )

**Comment by rogeralsing** [comment]
I'm very much on the fence for this one.
If it is about loading and unloading assemblies, then the quick answer should be no, as .NET itself does not support this so there is really no reason to invest more in that.

If it is about business logic, then I'm rather thinking if this shouldn't be modelled in user code somehow.
I'm 100% onboard of what @PotterDai says, 
>By introducing it as a method, it will simply encourage user to over-use it, which will greatly increase the chance of problems like duplicate grains, inconsistency

In Akka there are convenience constructs such as ActorSelection, which allows you to send messages to all child actors of some parent, or only actors matching foo* etc.
Handy, practical, but it leads to sloppy design where explicit concerns such as ownership maybe should be modelled explicitly, but instead is handled using string pattern matching.

ok, enough about Akka, but the problem is the same, if you introduce a technical solution to what really is a business problem, then you are stuck in the hands of the framework, you cannot alter the behavior if there are new requirements emerging.
