### ISSUE TITLE
Cluster fail to stabilize after node kill

### ISSUE THREAD

**Issue by jrouaix** [AsynkronIT/protoactor-dotnet#403]
Ran some tests to ensure the problem reported on gitter was not our stack fault.
And I seems I can reproduce it.

![image](https://user-images.githubusercontent.com/2705498/41046555-eb4d41a0-69aa-11e8-98aa-82c1c21189dc.png)

To reproduce : 
Run a cluster with some nodes, then kill any node. 
The cluster won't ever recover properly and a sh!t load of errors is passing in the VS debug window.

**Comment by jrouaix** [comment]
You can find details about the code I ran today in this branch : https://github.com/jrouaix/protoactor-dotnet/tree/cluster-stability-test

⚠️ I updated consul (it changed nothing), it took me to remove my /tmp/consul folder so the single node consul agree to start properly

**Comment by rogeralsing** [comment]
Will look into this. 👍

**Comment by jrouaix** [comment]
Any update on this one ? Do you need me to dig something to help ?

**Comment by jrouaix** [comment]
@rogeralsing ? any update on this one ? Is it related to the https://github.com/AsynkronIT/protoactor-dotnet/issues/411 refactoring you wanna do ?

**Comment by jrouaix** [comment]
My bad it was this branch : https://github.com/jrouaix/protoactor-dotnet/tree/cluster-stability-tests . with an 's' at the end. 

Still, kill one node and nothing work anymore.

**Comment by alexeyzimarev** [comment]
I think I have some insights now about this issue. The read address of an endpoint is different from the advertised address. I kind of understand the reason behind it, but still not sure if it is needed.

The result is that at some point when a node shuts down and anther node enters the cluster, and these nodes are different, somehow they differ in advertised and real addresses.

Example from the log (using the cluster stability test):

```
dbug: Proto.Remote.EndpointManager[0]
      Forwarding message for 127.0.0.1:53844 through EndpontWriter { "Address": "127.0.0.1:53822", "Id": "EndpointSupervisor/$11613" }
```

I will look closer to the remote configuration, maybe I can figure out how this happens.

**Comment by alexeyzimarev** [comment]
Ok, there were some issues, mostly with Consul provider. I spent a couple of days fixing it.

First, I refactored it to be done in actors instead of threads. Not only in uses less threads, but it is now more resilient. Then, I handled these cases:

- Service recovery after it was unregistered by Consul. The current version just crashes.
- Everything is asynchronous
- Consul has 1 minute minimal dereg timeout and the default in Proto.Actor is 30 sec, it was never working. I made it working by adding some code that handles such cases.
- All services were reported as alive althoug Consul returns some health checks failed, it never worked before.

API change - some methods are now async, I believe it's related to `Remote`.

I added some more logging but I don't want to merge those changes. I think, overall, logging needs more attention.
