### ISSUE TITLE
hello world guide code is not working on .net  core

### ISSUE THREAD

**Issue by Newp** [AsynkronIT/protoactor-dotnet#456]
hello world usage code 

var props = Actor.FromProducer(() => new HelloActor());
var pid = Actor.Spawn(props);

but Actor code is like this

    public static class Actor
    {
        public static readonly Task Done;
        public static EventStream EventStream { get; }
    }

so this code is not working at first.

**Comment by potterdai** [comment]
@Newp Hi, thank you for reporting! Probably the code is from an older version of ProtoActor?
The latest HelloWorld code is here:
https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/examples/HelloWorld/Program.cs

Since last summer there is a major update on ProtoActor's API, now the code should look like this:
```
var context = new RootContext();
var props = Props.FromProducer(() => new HelloActor());
var pid = context.Spawn(props);
```

**Comment by Newp** [comment]
@PotterDai Hi, I checked that is working.
I saw document on [http://proto.actor/docs/dotnet/hello%20world](url)

I'll follow example repository. thank you

**Comment by potterdai** [comment]
@Newp Hmm, didn't update the official website, that's not good. Thank you for reporting!
