### ISSUE TITLE
Separate contrib to another repo

### ISSUE THREAD

**Issue by alexeyzimarev** [AsynkronIT/protoactor-dotnet#499]
We briefly discussed establishing a more open place for contributions that are mostly related to integrating Proto.Actor .NET with different infrastructure, like persistence, DI, clustering and so on.

Shall we do it? How is it aligned with repo structure for other langs?

**Comment by cpx86** [comment]
> Shall we do it? 

IMO definitely yes :)

> How is it aligned with repo structure for other langs?

I don't think that's a problem. The only other really mature repo is the Go one and from what I can tell it doesn't contain anything like that anyway. And if the question comes up for protoactor-go then I guess it might depend a bit on what's the typical way to do it in Go repos.

@rogeralsing Do you agree?

The bigger question then would be what to move out.
- ✔️  Persistence providers - Seems like a given
- ✔️  Wire serializer - Fits the criteria as well I think
- ❓   Tracing - I would say probably yes, given that OpenTracing is in the process of becoming OpenTelemetry, but opentracing-dotnet seems to have quite some way to go before GA (still in it's first alpha version). OTOH tracing is becoming something that's considered a core feature of a library such as protoactor.
- ❓  Cluster providers - Since the beginning Consul has always been treated as the default provider due to it's light weight and ease of use. I'm not entirely convinced of this anymore. I could imagine a lot of users might prefer to use a k8s provider instead.
- ❓ DI/Scheduler/Persistence - Then there are a few ones which aren't related to integrating with other infrastructure, but that I'm not sure if they should be considered "core" or more as useful extensions. Should they stay in the main repo, or should some of them also be considered as "contrib" packages?

**Comment by alexeyzimarev** [comment]
>  but opentracing-dotnet seems to have quite some way to go before GA (still in it's first alpha version)

I assume you meant opentelemetry-dotnet. It's not that they have a long way to go, it's the OpenTelemetry as a standard is in alpha, so it's quite premature to base anything on it.

IMO we could implement embedded diagnostics using System.Diagnostics (diagnostic source and activity) and both OpenTracing and OpenTelemetry (in the future) could just use it.

**Comment by alexeyzimarev** [comment]
> I could imagine a lot of users might prefer to use a k8s provider instead.

That's true, we'd rather use a native k8s provider. I don't expect dramatic changes in clustering, except getting rid of singletons when the ActorSystem round is wrapped. I think that the Consul provider can happily live in the contrib repo.

**Comment by alexeyzimarev** [comment]
DI integration for the Microsoft default ASP.NET Core DI container is in the contrib folder already, so I think it should be moved among other things.

**Comment by cpx86** [comment]
> I assume you meant opentelemetry-dotnet. It's not that they have a long way to go, it's the OpenTelemetry as a standard is in alpha, so it's quite premature to base anything on it.
> IMO we could implement embedded diagnostics using System.Diagnostics (diagnostic source and activity) and both OpenTracing and OpenTelemetry (in the future) could just use it.

👍 Sounds like a plan

**Comment by alexeyzimarev** [comment]
I created https://github.com/AsynkronIT/protoactor-dotnet-contrib
Do we agree to move the existing contrib, persistence and Consul cluster?
I also suggest placing the simple cluster provider to Proto.Cluster project.

**Comment by Damian-P** [comment]
The proto files don't need to be in the same root directory ?

**Comment by alexeyzimarev** [comment]
@Damian-P what do you mean?

**Comment by Damian-P** [comment]
In the remote and the cluster csproj files we include the proto files:

`<Protobuf Include="Protos.proto" GrpcServices="Server" ProtoRoot=".; ..\..\src"/>`

They need the proto file in the Proto.Actor project

**Comment by alexeyzimarev** [comment]
Ah, yes, good point. I will check what are we referencing from the core project. Thanks for the heads-up 👍

**Comment by Damian-P** [comment]
Sorry I misunderstood. Only the providers will be moved... The Remote and the Cluster projects stay in the core project.

**Comment by alexeyzimarev** [comment]
Correct.

**Comment by cpx86** [comment]
Yep agree let's start out with those.

**Comment by alexeyzimarev** [comment]
Need to complete #501 first, projects in `contrib` will reference nuget packages.

**Comment by rogeralsing** [comment]
ok, lets go with this!

**Comment by alexeyzimarev** [comment]
Contrib projects are here https://github.com/AsynkronIT/protoactor-dotnet-contrib
