### ISSUE TITLE
Packages push issue

### ISSUE THREAD

**Issue by alexeyzimarev** [AsynkronIT/protoactor-dotnet#509]
I am logging the issue here so I won't forget. For some reason, packages aren't being properly pushed. I need to investigate the issue.

**Comment by sudsy** [comment]
I noticed that the actions are running in my forked repo whenever I push too. 

While I can see that it is good to run the tests on push, I am thinking that the publish to nuget shouldn't be running in the fork.

**Comment by alexeyzimarev** [comment]
@sudsy I agree it shouldn't be pushing. It is weird if if does, because the pack/push job should not run for PRs.

**Comment by alexeyzimarev** [comment]
But, packages are being pushed now from `dev` :)

**Comment by sudsy** [comment]
> @sudsy I agree it shouldn't be pushing. It is weird if if does, because the pack/push job should not run for PRs.

It didn't happen when I did my PR.  I noticed it when I pulled the upstream changes for the dev branch and then pushed those changes back to my fork. 

Seems like it could be fixed by an [if conditional](https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions) for the publish to nuget task:

`if: github.repository == 'AsynkronIT/protoactor-dotnet'`

**Comment by alexeyzimarev** [comment]
Ah, yes, it happens for me too. It can also be fixed if you go to your fork settings and disable actions.
