### ISSUE TITLE
How to rolling update protoactor cluster gracefully?

### ISSUE THREAD

**Issue by cupen** [AsynkronIT/protoactor-dotnet#558]
The feature [Multiple Activations], it will causing states overrided by each actors with the same `ID` when the cluster nodes growing or shrinking. It seems that could be resolved by `IdentityLookup.cs` https://github.com/AsynkronIT/protoactor-dotnet/issues/543 .
Any suggestions?

btw: I use `protoactor-go`. I'm experimenting this at https://github.com/AsynkronIT/protoactor-go/issues/404 . 

[Multiple Activations]: https://proto.actor/docs/cluster-partitions/#multiple-activations

**Comment by rogeralsing** [comment]
The issue of multiple activations are more or less gone with the introduction of IdentityLookup, e.g. MongoIdentityLookup.
The backing datasource becomes the source of truth.
It does add some spawning overhead, which is noticable when booting up a system, but due to PID caching, becomes negligible once the system is fully running.

This however needs to be ported over to Go.

**Comment by rogeralsing** [comment]
Replied on the Go issue tracker.
