### ISSUE TITLE
Scheduling messages - Semantics and middleware

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#97]
We now have two different PR's for scheduling messages.
Before picking an implementation, we should think about middleware semantics.

e.g.
Let's say we have a tracing middleware.
And now someone tries to schedule a message in 10 seconds.
Should that message go through the middleware?
Should the trace be continued from the original point forward to the receiver of the scheduled message?

This relates to #95  #69

**Comment by rogeralsing** [comment]
cc @jrouaix @raskolnikoov @cpx86

**Comment by rogeralsing** [comment]
Another thing to consider.
If we want to scheduler to use the middleware.

Lets say an actor schedules a message in 10 seconds, then the actor is stopped.
Should the message still be sent?
Should the message still go through the now dead middleware?

**Comment by jrouaix** [comment]
yep so, after comments from @cpx86 (https://github.com/AsynkronIT/protoactor-dotnet/pull/69#issuecomment-286994606) the implementation I proposed is using the SenderMiddleware.

Basically some extensions to the IContext (https://github.com/Bee-Htcpcp/protoactor-dotnet/blob/c94d5dea71e639e6902e10271cfa56f1adec5514/src/Proto.Scheduling/SchedulingExtensions.cs) wrapping the message to a "DelayMessage" instance, and tell to self this message. 
Then the middleware implementation catching this DelayMessage and use the IScheduler implementation given to Schedule the message.

The IScheduler interface is stupid simple : https://github.com/Bee-Htcpcp/protoactor-dotnet/blob/c94d5dea71e639e6902e10271cfa56f1adec5514/src/Proto.Scheduling/IScheduler.cs and the extensions methods are just proposing to delay a message to "Self". Because _in my opinion_ no one but the actor should delay something to it. (https://github.com/AsynkronIT/protoactor-dotnet/pull/69#issuecomment-286750465)

The activation is not yet covered, right now, a message delayed to a stopped actor will end in the dead letters (tested here : https://github.com/Bee-Htcpcp/protoactor-dotnet/blob/c94d5dea71e639e6902e10271cfa56f1adec5514/tests/Proto.Scheduling.Tests/InMemorySchedulerTests.cs#L59)

I proposed to have 2 pipes : one Transcient & one Persisted, right now they are implemented just the same but we could introduce slight changes.

I don't know yet how this will integrate with "named actors" "cluster activation" in my opinion :
https://github.com/AsynkronIT/protoactor-dotnet/pull/69#issuecomment-286767424
- If a transient delayed message comes and the actor is no more alive, the message should be dropped, not even appearing in the dead letters
- If a Persisted message comes and the actor is no more alive, the actor should be respawned and state restored (don't know how to implement it yet)

**Comment by cpx86** [comment]
@rogeralsing 
>  Someone tries to schedule a message in 10 seconds. Should that message go through the middleware? Should the trace be continued?

Depends on whether the tracer supports asynchronous messages, and it's mostly up to the tracer middleware to try to decide what to do about it.

> The actor is stopped. Should the message still be sent? Should the message still go through the now dead middleware?

No. If the actor is stopped and someone calls e.g. `context.Tell` I think the best would be if it throws an error, so whoever is trying to send the message can detect that the context is actually dead.

@jrouaix 
>If a transient delayed message comes and the actor is no more alive, the message should be dropped, not even appearing in the dead letters

I think it would still be useful to put the messages in dead letter, since there might be subscribers to the dead letter event stream that are interested in knowing when this happens.

> If a Persisted message comes and the actor is no more alive, the actor should be respawned and state restored (don't know how to implement it yet)

I think due to how supervision works, this might not be possible to do. If an actor died because it failed repeatedly, that means the supervisor decided that there's no way to revive the actor, either because the error was unrecoverable or because the actor was restarted repeatedly but still kept failing. So if an actor is no longer alive, I think it should stay that way or be respawned manually.

**Comment by raskolnikoov** [comment]
I like the idea when it's an extension to IContext instead of an interface that we need to pass to the actor and every scheduler needs to act like the other scheduler library out there. For example if I like to use Quartz or FluentScheduler I could use them in the same actor with these example usage:

```
context.FluentScheduler.Schedule<MyJob>().ToRunNow().AndEvery(2).Seconds();
```

or

```
IJobDetail job = JobBuilder.Create<HelloJob>()
                    .WithIdentity("job1", "group1")
                    .Build();

ITrigger trigger = TriggerBuilder.Create()
    .WithIdentity("trigger1", "group1")
    .StartNow()
    .WithSimpleSchedule(x => x
        .WithIntervalInSeconds(10)
        .RepeatForever())
    .Build();

context.Quartz.ScheduleJob(job, trigger);
```

**Comment by rogeralsing** [comment]
I very much like the idea of not having a shared interface and instead having usecase specific impls like @raskolnikoov describe
**duplication is far cheaper than the wrong abstraction.**

**Comment by jrouaix** [comment]
Well, the more I think about it, the more I think you're right. Too risky too bound the core librairy with some weak abstraction.

But this feature is still pretty needed, how do you want to implement it ?

As discussed here (https://github.com/AsynkronIT/protoactor-dotnet/issues/99) where do you want we push PR ?
